# Generated by Django 3.2.15 on 2024-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('date_of_journey', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('baggage_space', models.CharField(max_length=10)),
                ('is_checked', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
